ToTime(12,49,58,True)
now(00:00:04) to(12:49:58) inc(46194)
ToTime(12,54,58,True)
now(12:50:07) to(12:54:58) inc(291)
ToTime(12,59,58,True)
now(12:55:05) to(12:59:58) inc(293)
GE_EXC 2016-3-26 13:0:12 LogicServer can't distribute role msg(3295). roleId(42958262894624)
GE_EXC 2016-3-26 13:0:16 LogicServer can't distribute role msg(3295). roleId(42958262894626)
GE_EXC 2016-3-26 13:1:7 LogicServer can't distribute role msg(3295). roleId(42958262894624)
GE_EXC 2016-3-26 13:2:58 LogicServer can't distribute role msg(3295). roleId(42958262894626)
GE_EXC 2016-3-26 13:3:57 LogicServer can't distribute role msg(3295). roleId(42958262894627)
GE_EXC 2016-3-26 13:5:57 LogicServer can't distribute role msg(3295). roleId(42958262894625)
GE_EXC 2016-3-26 13:6:1 LogicServer can't distribute role msg(3295). roleId(42958262894625)
GE_EXC 2016-3-26 13:6:3 LogicServer can't distribute role msg(3295). roleId(42958262894625)
GE_EXC 2016-3-26 13:6:5 LogicServer can't distribute role msg(3295). roleId(42958262894625)
GE_EXC 2016-3-26 13:6:23 LogicServer can't distribute role msg(3295). roleId(42958262894625)
GE_EXC 2016-3-26 13:6:26 LogicServer can't distribute role msg(3295). roleId(42958262894625)
ToTime(19,49,58,True)
now(13:07:53) to(19:49:58) inc(24125)
ToTime(19,59,58,True)
now(19:50:08) to(19:59:58) inc(590)
20:20:41 GE_EXC, role(42958262894629) do command(FightEnd(role) #跳过战斗) error.
20:20:41 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 1, in <module>
NameError: name 'FightEnd' is not defined
20:20:48 GE_EXC, role(42958262894629) do command(FightEnd(role) #跳过战斗) error.
20:20:48 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 1, in <module>
NameError: name 'FightEnd' is not defined
20:21:18 GE_EXC, role(42958262894629) do command(FightEnd(role) #跳过战斗) error.
20:21:18 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 1, in <module>
NameError: name 'FightEnd' is not defined
20:21:53 GE_EXC, role(42958262894629) do command(FightEnd(role) #跳过战斗) error.
20:21:53 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 1, in <module>
NameError: name 'FightEnd' is not defined
5:16:16 GE_EXC, role(42958262894637) do command(#设置在线时长，XXX分钟
role.SetI16(320,XXX)
) error.
5:16:16 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 2, in <module>
NameError: name 'XXX' is not defined
5:20:29 GE_EXC, role(42958262894638) do command(#设置在线时长，XXX分钟
role.SetI16(340,XXX)
) error.
5:20:29 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 2, in <module>
NameError: name 'XXX' is not defined
5:22:2 GE_EXC, error in teamtower NextNPC index (2), (2)
ToTime(12,49,58,True)
now(05:22:44) to(12:49:58) inc(26834)
ToTime(12,59,58,True)
now(12:50:06) to(12:59:58) inc(592)
13:0:14 GE_EXC, DailyDo can not find index:(18) in DailyDo_Dict
13:0:18 GE_EXC, DailyDo can not find index:(18) in DailyDo_Dict
ToTime(13,14,58,True)
now(13:00:52) to(13:14:58) inc(846)
ToTime(19,29,58,True)
now(13:16:03) to(19:29:58) inc(22435)
ToTime(19,49,58,True)
now(19:30:55) to(19:49:58) inc(1143)
ToTime(19,54,58,True)
now(19:50:03) to(19:54:58) inc(295)
ToTime(19,58,58,True)
now(19:55:01) to(19:58:58) inc(237)
ToTime(19,59,58,True)
now(19:59:02) to(19:59:58) inc(56)
ToTime(20,29,58,True)
now(20:01:29) to(20:29:58) inc(1709)
20:30:17 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
20:30:26 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
20:30:32 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
20:30:33 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
20:30:34 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
20:30:35 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
20:30:37 Traceback (most recent call last):
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 1010, in RequestDDLuckyDraw
    LuckyDraw(role, backFunId)
  File "../PyCode/Game/Activity/DemonDefense/DemonDefenseMgr.py", line 514, in LuckyDraw
    addMoney = config.moneyBase_fcm * multiple
AttributeError: 'LuckyDrawBase' object has no attribute 'moneyBase_fcm'
ToTime(21,4,58,True)
now(20:34:35) to(21:04:58) inc(1823)
ToTime(21,8,58,True)
now(21:05:34) to(21:08:58) inc(204)
ToTime(21,9,58,True)
now(21:09:02) to(21:09:58) inc(56)
ToTime(21,29,58,True)
now(21:11:02) to(21:29:58) inc(1136)
DukeOnDuty.SetDukeUnion is OK {1: 655491076, 2: 2, 3: [], 4: 1, 5: 655491076}
ToTime(22,59,58,True)
now(21:38:08) to(22:59:58) inc(4910)
23:29:55 GE_EXC, ToLevel level (50) less nowLevel (61)
23:29:55 GE_EXC, role(42958262894636) do command(role.ToLevel(50)
role.SetVIP(10)
role.IncMoney(9999999999)
role.IncBindRMB(999999)
role.IncReputation(100000)
role.IncUnbindRMB_Q(999999)) error.
23:29:55 Traceback (most recent call last):
  File "../PyCode/Game/Role/Command.py", line 58, in OnCommandReturn
    DoRoleCommand(role, command)
  File "../PyCode/Game/Role/Command.py", line 86, in DoRoleCommand
    exec(command)
  File "<string>", line 2, in <module>
RuntimeError: C++ obj is NULL!
DEGroupBuy DE_GROUPBUY_CNT and recordRole_Set: 0 set([])
DukeOnDuty.SetDukeUnion is OK {1: 655491076, 2: 4, 3: [], 4: 1, 5: 655491076}
DEGroupBuy DE_GROUPBUY_CNT and recordRole_Set: 0 set([])
